server:
  port: 80

spring:
  application:
    name: hystrix-order-service

eureka:
  client:
    #    表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    #    是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      注册进单机的eureka
      #      defaultZone: http://localhost:7001/eureka
      #      注册进集群的eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#设置OpenFeign客户端超时时间(OpenFeign默认已经整合了ribbon),客户端超时时间默认一秒
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间
  ConnecTimeout: 5000

# 用于服务降级 在注解@FeignClient 中添加fallbackFactory 属性值
feign:
  hystrix:
    enabled: true  # 在feign中开启 hystrix

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000