server:
  port: 9527

spring:
  application:
    name: littlebird-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
#          lb:开启负载均衡
          uri: lb://payment-service
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          predicates:
#            - uri + Path 配置的路径才允许访问
            - Path=/getPayment/**  # 断言，路径相匹配的进行路由
#            - 时间点之后才允许访问
#            - After=2021-01-26T22:46:14.126+08:00[GMT+08:00]
#            - 时间点之前才允许访问
#            - Before=2021-01-26T22:46:14.126+08:00[GMT+08:00]
#            - 时间段之间才可以访问
#            - Between=2021-01-26T22:46:14.126+08:00[GMT+08:00]，2021-01-26T22:46:14.126+08:00[GMT+08:00]
#            - 看有道笔记
#            - Cookie=username,slf
#            - 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Header=X-Request-Id, \d+
#            - GET请求方式才可以访问
#            - Method=GET
#            - 要有参数名username并且值要是整数才能访问
#            - Query=username, \d
#            - 访问地址的域名是如下格式才可以访问
#            - Host=localhost:**
        #            - Host=localhost:**
        - id: payment_routh2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: lb://payment-service
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/timeout  # 断言，路径相匹配的进行路由

# 注册进 eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: true
    fetch-registry: true
